OTP_PURPOSE_TRANSFER_VERIFICATION = "TRANSFER_VERIFICATION"
OTP_PURPOSE_LOGIN = "LOGIN"
OTP_PURPOSE_ACCOUNT_CHANGE = "ACCOUNT_CHANGE"
OTP_PURPOSE_ACCOUNT_FREEZE = "ACCOUNT_FREEZE"

OTP_PURPOSES = frozenset(
    {
        OTP_PURPOSE_TRANSFER_VERIFICATION,
        OTP_PURPOSE_LOGIN,
        OTP_PURPOSE_ACCOUNT_CHANGE,
        OTP_PURPOSE_ACCOUNT_FREEZE,
    }
)
